brew "gh"
brew "libyaml"
brew "mise"
brew "starship"
brew "stow"

cask "docker-desktop" unless system "/bin/test", "-e", "/usr/local/bin/docker"
cask "ghostty" unless system "/bin/test", "-e", "/Applications/Ghostty.app"
cask "zed" unless system "/bin/test", "-e", "/Applications/Zed.app"
cask "font-fira-code-nerd-font" unless system "/bin/test", "-e", "#{Dir.home}/Library/Fonts/FiraCodeNerdFont-Bold.ttf"
