#!/bin/bash

# Install Homebrew packages
brew bundle --file="$(dirname "$0")/Brewfile"

# Symlink dotfiles via stow
cd "$(dirname "$0")" && stow --adopt -t ~ home && git checkout -- home/

# Remap Caps Lock to Control
hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,"HIDKeyboardModifierMappingDst":0x7000000E0}]}' > /dev/null
