call pathogen#infect()

" colorscheme twilight
syntax enable
set guicursor=a:blinkon0
set guifont=Monaco:h10
set background=dark
colorscheme solarized

" Disable toolbar on startup
set guioptions-=T

nnoremap <D-e> :NERDTree<CR>

" fullscreen maximizes vertically AND horizontally
set fuoptions=maxvert,maxhorz

" Disable bell.
set vb t_vb=
